# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded cluster 0.3 [list source [file join $dir cluster.tcl]]
package ifneeded cluster::swarm 0.2 [list source [file join $dir swarm.tcl]]
package ifneeded cluster::vcompare 0.1 [list source [file join $dir vcompare.tcl]]
package ifneeded cluster::virtualbox 0.1 [list source [file join $dir virtualbox.tcl]]
